"""init schema

Revision ID: 3ad199e3b0aa
Revises: 
Create Date: 2025-09-06 12:25:03.919398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad199e3b0aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firstname', sa.String(length=225), nullable=False),
    sa.Column('lastname', sa.String(length=225), nullable=False),
    sa.Column('username', sa.String(length=225), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_table_id'), 'users_table', ['id'], unique=False)
    op.create_table('notes_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=False),
    sa.Column('note_pad', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_table_id'), 'notes_table', ['id'], unique=False)
    op.create_index(op.f('ix_notes_table_owner_id'), 'notes_table', ['owner_id'], unique=False)
    op.create_index(op.f('ix_notes_table_title'), 'notes_table', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_table_title'), table_name='notes_table')
    op.drop_index(op.f('ix_notes_table_owner_id'), table_name='notes_table')
    op.drop_index(op.f('ix_notes_table_id'), table_name='notes_table')
    op.drop_table('notes_table')
    op.drop_index(op.f('ix_users_table_id'), table_name='users_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
