name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    defaults:
         run:
           shell: bash

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run migrations
        run: |
          python manage.py migrate || echo "No migrations found"

      - name: Run tests
        run: pytest -q
        
      - name: Verify required env is present
        run: |
          missing=0
          for v in SECRET_KEY REFRESH_SECRET_KEY ALGORITHM ACCESS_TOKEN_EXPIRE_MINUTES; do
            if [ -z "${!v}" ]; then
              echo "::error::$v is not set (check Settings > Secrets and variables > Actions)"
              missing=1
            fi
          done
          if [ "$missing" = "1" ]; then exit 1; fi

