name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: notedb_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres -d notedb_test"
          --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      SECRET_KEY: dev-secret
      REFRESH_SECRET_KEY: dev-refresh-secret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: '30'

      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/notedb_test

      RUN_DB_BOOTSTRAP: '1'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations (optional)
        run: alembic upgrade head || echo "No migrations found"

      - name: Run tests
        run: pytest -q
